/vis/open HepRepFile
/vis/drawVolume
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
/vis/scene/add/axes 0 0 0 1 m
# Draw hits at end of event:
#/vis/scene/add/hits
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
/vis/viewer/refresh
/vis/viewer/flush
#hard coded position and direction for gun
/gun/particle neutron
/gun/energy 2.5 MeV
/gun/position 0 0 0 cm
/gun/direction  1 1 1

#if you want make a run with particle
#/tracking/verbose 1
/run/beamOn 10
#

